import http from 'node:http';import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {chromium} from 'playwright-core';
const root=path.resolve('.'),types={'.html':'text/html','.css':'text/css','.js':'text/javascript','.mind':'application/octet-stream','.png':'image/png','.svg':'image/svg+xml'};
const server=http.createServer((req,res)=>{const url=req.url.split('?')[0]==='/'?'/index.html':req.url.split('?')[0];const f=path.resolve(root,'.'+decodeURIComponent(url));if(!f.startsWith(root)||!fs.existsSync(f)||fs.statSync(f).isDirectory()){res.writeHead(404);res.end();return}res.writeHead(200,{'Content-Type':types[path.extname(f)]||'application/octet-stream'});fs.createReadStream(f).pipe(res)});await new Promise(ok=>server.listen(4174,'127.0.0.1',ok));
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--use-gl=angle','--use-angle=swiftshader']});
const errors=[];try{const page=await browser.newPage({viewport:{width:1365,height:768}});page.on('pageerror',e=>errors.push(e.stack));
  await page.goto('http://127.0.0.1:4174/');assert.match(await page.title(),/Antofagasta/);assert.equal(await page.locator('a[href^="ar.html"]').count(),1);assert.equal(await page.locator('a[href^="viewer.html"]').count(),1);await page.screenshot({path:'work/landing.png'});
  await page.goto('http://127.0.0.1:4174/viewer.html');await page.waitForFunction(()=>window.plantModel?.pickables?.length===8,{timeout:30000});await page.locator('[data-scenario="surplus"]').click();assert.equal(await page.locator('#scenario-title').textContent(),'Excedente solar');assert.match(await page.locator('#metrics').textContent(),/75 kg\/h/);assert.match(await page.locator('#scenario-action').textContent(),/Sol intenso/);await page.waitForTimeout(900);assert.ok(await page.evaluate(()=>scene.renderer.info.render.calls>100));assert.ok(await page.evaluate(()=>plantModel.sunGroup.scale.x>1.5));await page.waitForFunction(()=>plantModel.packets.some(p=>p.path===2&&p.mesh.visible));await page.screenshot({path:'work/viewer.png'});
  await page.locator('[data-scenario="use"]').click();assert.match(await page.locator('#scenario-action').textContent(),/Abastecimiento/);const loading=await page.evaluate(()=>{plantModel.started=performance.now()-1500;plantModel.tick();return {first:plantModel.truckA.visible,second:plantModel.truckB.visible,tankFlow:plantModel.packets.some(p=>p.path===3&&p.mesh.visible)}});assert.deepEqual(loading,{first:true,second:false,tankFlow:true});const arriving=await page.evaluate(()=>{plantModel.started=performance.now()-5500;plantModel.tick();return {first:plantModel.truckA.visible,second:plantModel.truckB.visible,x:plantModel.truckB.position.x}});assert.equal(arriving.first,false);assert.equal(arriving.second,true);assert.ok(arriving.x>-.42&&arriving.x<.24);assert.match(await page.locator('#scenario-phase').textContent(),/se acerca/);const secondLoading=await page.evaluate(()=>{plantModel.started=performance.now()-8000;plantModel.tick();return {visible:plantModel.truckB.visible,x:plantModel.truckB.position.x}});assert.equal(secondLoading.visible,true);assert.ok(Math.abs(secondLoading.x-.24)<.01);assert.match(await page.locator('#scenario-phase').textContent(),/Camión 2 cargando/);await page.screenshot({path:'work/viewer-use.png'});
  const geometry=await page.evaluate(()=>({roadZ:plantModel.road.position.z,roadHalfWidth:plantModel.road.geometry.parameters.depth/2,truckZ:plantModel.truckB.position.z,hose:plantModel.fuelHose.visible,sunStreams:plantModel.sunStreams.length,terrainTexture:!!plantModel.root.children[1].material[2].map,roadTexture:!!plantModel.road.material[2].map}));assert.ok(Math.abs(geometry.truckZ-geometry.roadZ)<.02);assert.ok(geometry.roadHalfWidth>.07);assert.equal(geometry.hose,true);assert.equal(geometry.sunStreams,3);assert.ok(geometry.terrainTexture&&geometry.roadTexture);const departure=await page.evaluate(()=>{plantModel.started=performance.now()-3100;plantModel.tick();return{hose:plantModel.fuelHose.visible,dust:plantModel.truckA.userData.dust.some(p=>p.visible),second:plantModel.truckB.visible,x:plantModel.truckA.position.x}});assert.equal(departure.hose,false);assert.equal(departure.dust,true);assert.equal(departure.second,false);assert.ok(departure.x>.24);await page.screenshot({path:'work/viewer-departure.png'});const approach=await page.evaluate(()=>{plantModel.started=performance.now()-4800;plantModel.tick();return plantModel.truckB.userData.dust.some(p=>p.visible)});assert.equal(approach,true);await page.screenshot({path:'work/viewer-arrival.png'});
  const sun=await page.evaluate(()=>{const mesh=plantModel.pickables.find(o=>o.userData.infoId==='sun');const p=mesh.getWorldPosition(new AFRAME.THREE.Vector3()).project(scene.camera),r=scene.canvas.getBoundingClientRect();return{x:r.left+(p.x+1)*r.width/2,y:r.top+(1-p.y)*r.height/2}});await page.mouse.click(sun.x,sun.y);assert.equal(await page.locator('#info-title').textContent(),'Sol de Atacama');await page.locator('#close-info').click();
  const pick=await page.evaluate(()=>{const mesh=plantModel.pickables.find(o=>o.userData.infoId==='electro');const p=mesh.getWorldPosition(new AFRAME.THREE.Vector3()).project(scene.camera),r=scene.canvas.getBoundingClientRect();return{x:r.left+(p.x+1)*r.width/2,y:r.top+(1-p.y)*r.height/2}});await page.mouse.click(pick.x,pick.y);assert.equal(await page.locator('#info-title').textContent(),'Electrolizador');await page.locator('#close-info').click();
  await page.setViewportSize({width:1200,height:940});await page.goto('http://127.0.0.1:4174/marker.html?bn=1');assert.match(await page.locator('#marker-image').getAttribute('src'),/marker-bn\.png/);await page.screenshot({path:'work/marker-print-bw.png'});
  const mobile=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:1,isMobile:true,hasTouch:true});mobile.on('pageerror',e=>errors.push(e.stack));await mobile.goto('http://127.0.0.1:4174/ar.html');await mobile.waitForFunction(()=>!!window.plantModel,{timeout:30000});assert.equal(await mobile.locator('#start-ar').count(),1);assert.ok(await mobile.locator('.marker-preview').isVisible());assert.match(await mobile.locator('#start-overlay').textContent(),/otro computador o tablet/);assert.match(await mobile.locator('#start-overlay').textContent(),/marker.html/);assert.equal((await mobile.request.get('http://127.0.0.1:4174/assets/marker/antofagasta-h2.mind')).status(),200);await mobile.screenshot({path:'work/ar-start.png'});await mobile.goto('http://127.0.0.1:4174/marker.html?bn=1');assert.match(await mobile.locator('#marker-image').getAttribute('src'),/marker-bn\.png/);assert.ok(await mobile.locator('#marker-image').evaluate(img=>img.complete&&img.naturalWidth>0));await mobile.goto('http://127.0.0.1:4174/viewer.html');await mobile.waitForFunction(()=>window.plantModel?.pickables?.length===8,{timeout:30000});await mobile.waitForTimeout(500);assert.ok(await mobile.evaluate(()=>scene.renderer.info.render.calls>100));const layout=await mobile.evaluate(()=>{const b=new AFRAME.THREE.Box3().setFromObject(plantModel.root.children[0]),r=scene.canvas.getBoundingClientRect();let bottom=-Infinity;for(const x of [b.min.x,b.max.x])for(const y of [b.min.y,b.max.y])for(const z of [b.min.z,b.max.z]){const p=new AFRAME.THREE.Vector3(x,y,z).project(scene.camera);bottom=Math.max(bottom,r.top+(1-p.y)*r.height/2)}return{bottom,panelTop:document.querySelector('.dashboard').getBoundingClientRect().top,sunY:plantModel.sunGroup.position.y}});assert.ok(layout.bottom<layout.panelTop-20,JSON.stringify(layout));assert.ok(layout.sunY>.3);await mobile.screenshot({path:'work/viewer-mobile.png'});
  assert.deepEqual(errors,[]);console.log('Smoke OK. Screenshots: work/landing.png, work/viewer.png, work/ar-start.png');
}finally{await browser.close();server.close()}
