import http from 'node:http';import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {chromium} from 'playwright-core';
const root=path.resolve('.'),types={'.html':'text/html','.css':'text/css','.js':'text/javascript','.mind':'application/octet-stream','.png':'image/png','.svg':'image/svg+xml'};
const server=http.createServer((req,res)=>{const url=req.url.split('?')[0]==='/'?'/index.html':req.url.split('?')[0];const f=path.resolve(root,'.'+decodeURIComponent(url));if(!f.startsWith(root)||!fs.existsSync(f)||fs.statSync(f).isDirectory()){res.writeHead(404);res.end();return}res.writeHead(200,{'Content-Type':types[path.extname(f)]||'application/octet-stream'});fs.createReadStream(f).pipe(res)});await new Promise(ok=>server.listen(4174,'127.0.0.1',ok));
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--use-gl=angle','--use-angle=swiftshader']});
const errors=[];try{const page=await browser.newPage({viewport:{width:1365,height:768}});page.on('pageerror',e=>errors.push(e.stack));
  await page.goto('http://127.0.0.1:4174/');assert.match(await page.title(),/Antofagasta/);assert.equal(await page.locator('a[href^="ar.html"]').count(),1);assert.equal(await page.locator('a[href="viewer.html"]').count(),1);await page.screenshot({path:'work/landing.png'});
  await page.goto('http://127.0.0.1:4174/viewer.html');await page.waitForFunction(()=>window.plantModel?.pickables?.length===7,{timeout:30000});await page.locator('[data-scenario="surplus"]').click();assert.equal(await page.locator('#scenario-title').textContent(),'Excedente solar');assert.match(await page.locator('#metrics').textContent(),/75 kg\/h/);await page.waitForTimeout(900);assert.ok(await page.evaluate(()=>scene.renderer.info.render.calls>100));await page.screenshot({path:'work/viewer.png'});
  const pick=await page.evaluate(()=>{const mesh=plantModel.pickables.find(o=>o.userData.infoId==='electro');const p=mesh.getWorldPosition(new AFRAME.THREE.Vector3()).project(scene.camera),r=scene.canvas.getBoundingClientRect();return{x:r.left+(p.x+1)*r.width/2,y:r.top+(1-p.y)*r.height/2}});await page.mouse.click(pick.x,pick.y);assert.equal(await page.locator('#info-title').textContent(),'Electrolizador');await page.locator('#close-info').click();
  const mobile=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:1,isMobile:true,hasTouch:true});mobile.on('pageerror',e=>errors.push(e.stack));await mobile.goto('http://127.0.0.1:4174/ar.html');await mobile.waitForFunction(()=>!!window.plantModel,{timeout:30000});assert.equal(await mobile.locator('#start-ar').count(),1);assert.equal((await mobile.request.get('http://127.0.0.1:4174/assets/marker/antofagasta-h2.mind')).status(),200);await mobile.screenshot({path:'work/ar-start.png'});await mobile.goto('http://127.0.0.1:4174/viewer.html');await mobile.waitForFunction(()=>window.plantModel?.pickables?.length===7,{timeout:30000});await mobile.waitForTimeout(500);assert.ok(await mobile.evaluate(()=>scene.renderer.info.render.calls>100));await mobile.screenshot({path:'work/viewer-mobile.png'});
  assert.deepEqual(errors,[]);console.log('Smoke OK. Screenshots: work/landing.png, work/viewer.png, work/ar-start.png');
}finally{await browser.close();server.close()}
